### ISSUE TITLE
Simplify gdpr-replacement to make it Faker agnostic

### ISSUE THREAD

**Issue by fjgarlin** [machbarmacher/gdpr-dump#11]
I suggest accepting a series of formatters that might or might not be implemented via faker. Faker is still the way to go but might not be always suitable. We'd just need to create a map of key and how to map that key. 

This will also simplify the gdpr replacements expression. See below.

*Suggested gdpr-replacements*:
```{"tableName":{"columnName1":{"formatter":"username"},"columnName2":{"formatter":"password"},"columnName3":{"formatter":"email"}}}```

**Comment by bomoko** [comment]
This makes perfect sense - we can break the Faker dependency here.
On it.

**Comment by UB3RL33T** [comment]
Are there any plans to allow "unsupported" formatters? 
For now, the only formatters that are accepted are the whitelisted ones. Wouldn't it make sense to "pass through" unsupported formatters to Faker?

**Comment by amenk** [comment]
An option would also be to add as much possible formatters from faker to the white list in gdprdump...
Is there any specific reason to keep the whitelist so small?
