### ISSUE TITLE
mysqldump password behaviour?

### ISSUE THREAD

**Issue by maniac0s** [machbarmacher/gdpr-dump#22]
When using original mysqldump, I can write

mysqldump -u username -p db_name

And mysqldump will request for a passwort
Using gdpr-dump's mysqldump replacement, it doesn't understand that "db_name" might not be a password, instead it complains " Not enough arguments (missing: "db-name")." If I use the format

mysqldump db_name -u username -p
It tries to access the db without a password, doesn't request for a password.

I just don't like typing my password into the commandline, that's why I always use mysqldump as mentioned above.

Could you have it going like the original mysqldump: if -p is given but db-name appears missing, consider the last parameter the db-name and request for a password?

**Comment by bomoko** [comment]
Hi @maniac0s 
Very good point, and absolutely, yes!

The idea is really to have this be more or less a 100% drop-in replacement for mysqldump, and so we should definitely support this behavior.

I'll try work up a patch for this as soon as possible, and if there is anything else, please submit an issue (and PR if you're up for it).

**Comment by bomoko** [comment]
Added password fallback is in there - closing.
